name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Generate Subscription"]
    types: [completed]

jobs:
  deploy:  # 唯一作业，无需声明依赖关系
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: clash-config
        path: ./public

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./public

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
