name: Deploy to GitHub Pages

on:
  # 当 generate-subscription 工作流完成后触发
  workflow_run:
    workflows: ["Generate Subscription"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write  # 启用 Pages 部署权限
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: clash-config  # 必须与前一个工作流的 artifact 名称一致
        path: ./public

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./public

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
