name: Generate Subscription

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 12 * * *'  # 每天 UTC 时间 12:00 自动运行

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予写入仓库的权限
      actions: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests pyaes

    - name: Generate config
      run: |
        echo "::group::生成过程日志"
        python generate_subscription.py > clash_config.yaml
        echo "::endgroup::"
        
        echo "::group::配置文件预览"
        head -n 20 clash_config.yaml
        echo "::endgroup::"

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # 升级到最新版本
      with:
        name: clash-config
        path: clash_config.yaml
        retention-days: 365  # 设置较长的保留时间

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and push
      run: |
        git add clash_config.yaml
        git commit -m "Auto-update config at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        # 使用 GITHUB_TOKEN 认证推送
        git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
