name: Generate Subscription

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 12 * * *'  # 每天 UTC 时间 12:00 自动运行

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # 读取仓库内容权限
      actions: read  # 读取动作权限
      pages: write  # 写入 Pages 权限
      id-token: write  # 用于身份验证
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # 指定 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests pyaes

    - name: Generate config
      run: |
        echo "::group::生成过程日志"
        python generate_subscription.py > clash_config.yaml
        echo "::endgroup::"
        
        echo "::group::配置文件预览"
        head -n 20 clash_config.yaml
        echo "::endgroup::"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: clash-config
        path: clash_config.yaml

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add clash_config.yaml
        git commit -m "Auto-update config at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        git push

    - name: Post success message
      run: |
        echo "Subscription config updated successfully!"
