- name: Update Subscription Link File # 步骤名称：更新订阅链接文件
     uses: actions/github-script@v6 # 使用 actions/github-script@v6 action，用于执行 JavaScript 脚本与 GitHub API 交互
     with:
       script: |
         console.log('这是一个简化的测试脚本。如果日志中看到这句话，说明 YAML 文件解析正常。');
